### ISSUE TITLE
Нужна схема базы и миграции

### ISSUE THREAD

**Issue by svetlyak40wt** [aplakhov/notq#4]
Иначе как у себя тестовый инстанс поднять?

**Comment by 1e9y** [comment]
Я хотел бы починить баг со свертыванием и добавить темную тему, но без контейнера или seed-скрипта приложение невозможно поднять локально.

**Comment by aplakhov** [comment]
Так, я починил развертывание с нуля и сделал README "как поднять у себя", в котором в том числе есть пункт про инициализацию БД.
Это формально не то же самое, что "схема базы и миграции", но, мне кажется, удовлетворяет исходную потребность. Закрываем тикет?

**Comment by svetlyak40wt** [comment]
Я бы поправил инструкцию, заменив:

```
pip install -e .
```

на

```
python3 -m venv env
source env/bin/activate
pip install -e .
```

чтобы не захламлять систему пакетами.

В остальном норм. Я проверил, работает!
